language: cpp

addons:
  apt:
    packages:
      - libsdl2-dev
      - libglew-dev
      - libftgl-dev
      - libsdl2-dev
      - libdevil-dev
      - clang-5.0
    sources:
      - llvm-toolchain-trusty-5.0

script: CC=clang-5.0 CXX=clang-5.0 make -j4
